# Generated by Django 3.2.19 on 2023-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizhimost', '0003_auto_20230501_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='tipcdelki',
            field=models.CharField(choices=[('kupit', 'Купить'), ('prodat', 'Продать'), ('snat', 'Снять'), ('cdat', 'Сдать')], default='kupit', max_length=16, verbose_name='Тип сделки'),
        ),
    ]
