# Generated by Django 3.2.18 on 2023-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizhimost', '0004_alter_dom_tipcdelki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='category',
            field=models.CharField(choices=[('kvartira', 'Квартиры'), ('komerch', 'Коммерческая недвижимость'), ('zagorod', 'Загородные дома'), ('garazh', 'Гаражи'), ('zemuch', 'Земельные участки'), ('newstroi', 'Новостройки')], default='kvartira', max_length=16, verbose_name='Категория недвижимости'),
        ),
    ]
