# Generated by Django 3.2.18 on 2023-05-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizhimost', '0005_alter_dom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='colkomnat',
            field=models.CharField(choices=[('stud', 'Студия'), ('1k', '1'), ('2k', '2'), ('3k', '3'), ('4k', '4+')], default='1k', max_length=16, verbose_name='Кол-во комнат'),
        ),
    ]
