# Generated by Django 3.2.18 on 2023-05-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizhimost', '0007_auto_20230511_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='colkomnat',
            field=models.CharField(choices=[('not', '---------'), ('stud', 'Студия'), ('1k', '1'), ('2k', '2'), ('3k', '3'), ('4k', '4+')], default='not', max_length=16, verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='tipcdelki',
            field=models.CharField(choices=[('kupit', 'Купить'), ('prodat', 'Продать'), ('snat', 'Снять'), ('cdat', 'Сдать')], default='kupit', max_length=16, verbose_name='Тип сделки'),
        ),
    ]
