# Generated by Django 3.2.19 on 2023-05-24 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nedvizhimost', '0008_auto_20230511_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='favorit',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
