# Generated by Django 3.2.19 on 2023-06-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizhimost', '0009_dom_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='priceot',
            field=models.BooleanField(default=True, verbose_name='Цена от'),
        ),
    ]
