# Generated by Django 3.2.19 on 2023-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizhimost', '0009_dom_favorit'),
        ('users', '0005_auto_20230523_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='nedvizhimost.Dom'),
        ),
    ]
