# Generated by Django 3.2.19 on 2023-05-04 09:31

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zag', models.TextField(blank=True, max_length=3000, verbose_name='Заголовок')),
                ('post', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Прайс на услуги',
                'verbose_name_plural': 'Прайс на услуги',
                'ordering': ('id',),
            },
        ),
    ]
