# Generated by Django 3.2.19 on 2023-05-04 10:06

from django.db import migrations, models
import django_ckeditor_5.fields
import uslugi.models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zag', models.CharField(blank=True, max_length=3000, verbose_name='Заголовок')),
                ('tipusl', models.CharField(choices=[('usl1', 'Юридические услуги'), ('usl2', 'Риэлторские услуги')], default='usl1', max_length=16, verbose_name='Тип услуги')),
                ('tipcdelki', models.CharField(choices=[('doc', 'Оформление документов'), ('dogovor', 'Договоры'), ('soprsdel', 'Сопровождение сделок'), ('oformldoc', 'Оформление наследства')], default='doc', max_length=16, verbose_name='Категория услуги')),
                ('image_zast', models.ImageField(upload_to=uslugi.models.get_file_image_zast_usl, verbose_name='Заставка услуги')),
                ('post', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент')),
                ('best', models.BooleanField(default=False, verbose_name='Лучшее предложение')),
                ('price', models.IntegerField(default='0', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='priceuslugi',
            name='zag',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Заголовок'),
        ),
    ]
