# Generated by Django 3.2.18 on 2023-05-04 15:24

from django.db import migrations, models
import uslugi.models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_auto_20230504_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='image_zast_verh',
            field=models.ImageField(default=12, upload_to=uslugi.models.get_file_image_zast_usl_form, verbose_name='Заставка услуги в форму'),
            preserve_default=False,
        ),
    ]
