# Generated by Django 3.2.18 on 2023-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0003_uslugi_image_zast_verh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='tipcdelki',
            field=models.CharField(choices=[('doc', 'Оформление документов'), ('dogovor', 'Договоры'), ('soprsdel', 'Сопровождение сделок'), ('oformldoc', 'Оформление наследства'), ('zhi1', 'Жилые помещения'), ('zhi2', 'Загородная недвижимость'), ('zhi3', 'Нежилые помещения'), ('zhi4', 'коммерческая недвижимость')], default='doc', max_length=16, verbose_name='Категория услуги'),
        ),
    ]
