# Generated by Django 3.2.19 on 2023-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0004_alter_uslugi_tipcdelki'),
    ]

    operations = [
        migrations.AddField(
            model_name='uslugi',
            name='description',
            field=models.CharField(blank=True, max_length=350, verbose_name='Заголовок Description'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URl'),
        ),
        migrations.AddField(
            model_name='uslugi',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок Title'),
        ),
        migrations.AlterField(
            model_name='priceuslugi',
            name='zag',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Заголовок'),
        ),
    ]
