# Generated by Django 3.2.19 on 2023-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0006_auto_20230916_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='uslugi',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='uslugi',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
