# Generated by Django 3.2.19 on 2023-09-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0009_auto_20230917_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uslugi',
            name='vopotv',
        ),
        migrations.AddField(
            model_name='voprosotvet',
            name='usluga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uslugi.uslugi', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
