# Generated by Django 3.2.19 on 2023-12-05 15:09

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import invest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URl')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Title')),
                ('description', models.CharField(blank=True, max_length=350, verbose_name='Заголовок Description')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок H1')),
                ('post', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание')),
                ('introtext', models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('deistvie', models.CharField(choices=[('kupit', 'Купить'), ('prodat', 'Продать')], default='kupit', max_length=16, verbose_name='Действие')),
                ('tipcdelki', models.CharField(choices=[('apartament', 'Апартаменты'), ('kvartira', 'Квартиры'), ('komerch', 'Коммерческая недвижимость'), ('zagorod', 'Загородные дома')], default='apartament', max_length=16, verbose_name='Тип')),
                ('colkomnat', models.CharField(choices=[('not', '---------'), ('stud', 'Студия'), ('1k', '1'), ('2k', '2'), ('3k', '3'), ('4k', '4+')], default='not', max_length=16, verbose_name='Кол-во комнат')),
                ('ploshad', models.IntegerField(default='0', verbose_name='Площадь')),
                ('price', models.IntegerField(default='0', verbose_name='Цена')),

            ],
            options={
                'verbose_name': 'Инвестиции',
                'verbose_name_plural': 'Инвестиции',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='GalleryDom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=invest.models.get_file_image_foto, verbose_name='Фото объекта')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
                ('invest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.invest', verbose_name='Объект недвижимости')),
            ],
        ),
    ]
