# Generated by Django 3.2.19 on 2023-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='adres',
            field=models.CharField(default=True, max_length=555, verbose_name='Адрес'),
        ),
    ]
