# Generated by Django 3.2.19 on 2023-12-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_invest_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='adres',
            field=models.CharField(blank=True, max_length=555, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='TagInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=1000, verbose_name='Тег')),
                ('invest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invest.invest', verbose_name='Объект недвижимости')),
            ],
        ),
    ]
