# Generated by Django 3.2.19 on 2023-12-26 10:32

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_auto_20231205_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='country',
            field=models.CharField(choices=[('russia', 'Россия'), ('oae', 'ОАЭ')], default='russia', max_length=16, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='invest',
            name='drugoe',
            field=models.CharField(choices=[('remont', 'с ремонтом'), ('bezremont', 'без ремонта')], default='remont', max_length=16, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='invest',
            name='gotov',
            field=models.CharField(choices=[('gotov', 'строится'), ('sdan', 'сдан')], default='gotov', max_length=16, verbose_name='Готовность'),
        ),
        migrations.AddField(
            model_name='invest',
            name='infrastr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Инфраструктура'),
        ),
        migrations.AlterField(
            model_name='invest',
            name='introtext',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание(в карточку)'),
        ),
    ]
