# Generated by Django 3.2.18 on 2023-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian')], max_length=16, unique=True, verbose_name='Язык')),
                ('name_site', models.TextField(blank=True, verbose_name='Название сайта')),
                ('phone1', models.TextField(blank=True, verbose_name='Основной телефон')),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
                'ordering': ['language'],
            },
        ),
    ]
