# Generated by Django 3.2.18 on 2023-05-10 16:48

from django.db import migrations, models
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_zast', models.ImageField(upload_to=websitesetting.models.get_file_image_baner, verbose_name='Картинка')),
                ('url', models.CharField(blank=True, max_length=3000, verbose_name='Ссылка')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
            ],
            options={
                'verbose_name': 'Банеры на главную',
                'verbose_name_plural': 'Банеры на главную',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BankPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_zast', models.ImageField(upload_to=websitesetting.models.get_file_image_partner, verbose_name='Лого')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
            ],
            options={
                'verbose_name': 'Банки Партнеры',
                'verbose_name_plural': 'Банки Партнеры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_zast', models.ImageField(upload_to=websitesetting.models.get_file_image_partner, verbose_name='Лого')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
            ],
            options={
                'verbose_name': 'Наши Партнеры',
                'verbose_name_plural': 'Наши Партнеры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VoprosOtvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vopros', models.TextField(blank=True, max_length=3000, verbose_name='Вопрос')),
                ('otvet', models.TextField(blank=True, max_length=10000, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос - Ответ',
                'verbose_name_plural': 'Вопрос - Ответ',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='addr',
            field=models.TextField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='inst',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='maps',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Код карты'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Дополнительный телефон'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='teleg',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='vk',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='name_site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, verbose_name='Основной телефон'),
        ),
    ]
