# Generated by Django 3.2.18 on 2023-05-10 17:00

from django.db import migrations, models
import django_ckeditor_5.fields
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0003_websitecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'ordering': ['language'], 'verbose_name': 'Статический контент', 'verbose_name_plural': 'Статический контент'},
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='image_onas',
            field=models.ImageField(default=1, upload_to=websitesetting.models.get_file_image_flat, verbose_name='Картинка в блок на главную'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='image_rieltuslug',
            field=models.ImageField(default=1, upload_to=websitesetting.models.get_file_image_flat, verbose_name='Картинка Риэлт.услуг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='image_yuruslug',
            field=models.ImageField(default=1, upload_to=websitesetting.models.get_file_image_flat, verbose_name='Картинка Юр.услуг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_bankpartner',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание блока БАНКИ - ПАРТНЕРЫ'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_bonus',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание блока БОНУСЫ ОТ КОМПАНИЙ'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_onas',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст на страницу о нас'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_onas_glav',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст на главную'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_politic',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст политики конфидициальности '),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_rieltuslug',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст Риэлт.услуг'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_uslugi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст на страницу услуги'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='text_yuruslug',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст Юр.услуг'),
        ),
    ]
