# Generated by Django 3.2.18 on 2023-05-10 17:07

from django.db import migrations, models
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0004_auto_20230510_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='image_onas',
            field=models.ImageField(blank=True, null=True, upload_to=websitesetting.models.get_file_image_flat, verbose_name='Картинка в блок на главную'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='image_rieltuslug',
            field=models.ImageField(blank=True, null=True, upload_to=websitesetting.models.get_file_image_flat, verbose_name='Картинка Риэлт.услуг'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='image_yuruslug',
            field=models.ImageField(blank=True, null=True, upload_to=websitesetting.models.get_file_image_flat, verbose_name='Картинка Юр.услуг'),
        ),
    ]
