# Generated by Django 3.2.18 on 2023-05-11 07:44

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0005_auto_20230510_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voprosotvet',
            name='otvet',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=10000, verbose_name='Ответ'),
        ),
    ]
