# Generated by Django 3.2.19 on 2023-09-16 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0006_alter_voprosotvet_otvet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revius_klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Имя')),
                ('text', models.TextField(blank=True, max_length=6000, verbose_name='Отзыв')),
                ('kolstar', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Отзывы клиентов',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ('id',),
            },
        ),
    ]
