# Generated by Django 3.2.19 on 2023-09-16 18:21

from django.db import migrations, models
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0007_revius_klient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=websitesetting.models.get_file_image_office, verbose_name='Лого')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
            ],
            options={
                'verbose_name': 'В офисе – как дома',
                'verbose_name_plural': 'В офисе – как дома',
                'ordering': ('id',),
            },
        ),
    ]
