# Generated by Django 3.2.19 on 2023-09-16 19:12

from django.db import migrations, models
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0008_oficeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficeimg',
            name='image',
            field=models.ImageField(upload_to=websitesetting.models.get_file_image_office, verbose_name='Фото'),
        ),
    ]
