# Generated by Django 3.2.19 on 2023-09-17 07:54

from django.db import migrations, models
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0009_alter_oficeimg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusVam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=websitesetting.models.get_file_image_plus, verbose_name='Фото')),
                ('zag', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=6000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Преимущества для вас',
                'verbose_name_plural': 'Преимущества для вас',
                'ordering': ('id',),
            },
        ),
    ]
