# Generated by Django 3.2.19 on 2023-09-17 08:32

from django.db import migrations, models
import websitesetting.models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesetting', '0010_plusvam'),
    ]

    operations = [
        migrations.AddField(
            model_name='plusvam',
            name='imagemob',
            field=models.ImageField(default=12, upload_to=websitesetting.models.get_file_image_plusmob, verbose_name='Фото в мобилку'),
            preserve_default=False,
        ),
    ]
